In [3]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import pandas as pd
import pymysql
from sqlalchemy import create_engine

In [4]:
mysqlEngine = create_engine('mysql+pymysql://simgm:12345@localhost/stats')

In [5]:
df = pd.read_sql_table('v_hitroster', mysqlEngine)

In [6]:
teams = df['Team_Link'].unique()

In [7]:
teams

array(['2624080F263FE6FA7D0A02E73F171419',
       '3EAF5FB809DA07BB0E23DA1FD8E3579D',
       '7914BF152455EE72DD17B085A892ED79',
       '9B905E53B42C71170AA5EBA2FDA4FFFD',
       'B4AA5349B2781A1E68367A7A82EBDF02',
       'C495D44BBA0C49D40AA5EBA2FDA4FFFD',
       'C495D44BBA0C49D40FFC3B7900F5DE72',
       'C495D44BBA0C49D43859DC4E30555E86',
       'C495D44BBA0C49D44B8BAB4CC93E869F',
       'C495D44BBA0C49D460B6F102110B3422',
       'C495D44BBA0C49D4D43798954B3C4DD5',
       'C495D44BBA0C49D4F7B8E4092C7CF8C1'], dtype=object)

In [19]:
dfProgs = pd.read_sql_table('v_prog_list', mysqlEngine)

In [48]:
dfProgs = dfProgs.set_index('ID')

In [49]:
dfProgs

                                  Prog_Name
ID
10008    Franchise Progression (Petroshius)
10001                    Progressive (Long)
10007        SSG Replay Franchise (Rotroff)
10000                Year-By-Year (Rotroff)
10002                   24 Team (Strausler)
10005             New Progression (DiPalma)
10004                     Big Dawgs (Myers)
10006          Random Association (Various)
10013  Expansion Era Progression (Tonzillo)
10003          Through the Ages (LeLacheur)
10012          Win Place Show League (Lang)
10010    Franchise Progression 2 (Sherwood)
10011     Quick Franchise Decade (Sherwood)
10009      Franchise Progression (Sherwood)

In [25]:
options=[{'label': dfProgs['Prog_Name'], 'value': dfProgs['ID']} for progression in dfProgs]

In [26]:
options

[{'label': 0       Franchise Progression (Petroshius)
  1                       Progressive (Long)
  2           SSG Replay Franchise (Rotroff)
  3                   Year-By-Year (Rotroff)
  4                      24 Team (Strausler)
  5                New Progression (DiPalma)
  6                        Big Dawgs (Myers)
  7             Random Association (Various)
  8     Expansion Era Progression (Tonzillo)
  9             Through the Ages (LeLacheur)
  10            Win Place Show League (Lang)
  11      Franchise Progression 2 (Sherwood)
  12       Quick Franchise Decade (Sherwood)
  13        Franchise Progression (Sherwood)
  Name: Prog_Name, dtype: object, 'value': 0     10008
  1     10001
  2     10007
  3     10000
  4     10002
  5     10005
  6     10004
  7     10006
  8     10013
  9     10003
  10    10012
  11    10010
  12    10011
  13    10009
  Name: ID, dtype: int64}, {'label': 0       Franchise Progression (Petroshius)
  1                       Progressive (Long)
  2           SSG Replay Franchise (Rotroff)
  3                   Year-By-Year (Rotroff)
  4                      24 Team (Strausler)
  5                New Progression (DiPalma)
  6                        Big Dawgs (Myers)
  7             Random Association (Various)
  8     Expansion Era Progression (Tonzillo)
  9             Through the Ages (LeLacheur)
  10            Win Place Show League (Lang)
  11      Franchise Progression 2 (Sherwood)
  12       Quick Franchise Decade (Sherwood)
  13        Franchise Progression (Sherwood)
  Name: Prog_Name, dtype: object, 'value': 0     10008
  1     10001
  2     10007
  3     10000
  4     10002
  5     10005
  6     10004
  7     10006
  8     10013
  9     10003
  10    10012
  11    10010
  12    10011
  13    10009
  Name: ID, dtype: int64}]

In [50]:
options=[{'label': v, 'value': k} for k, v in dfProgs.items()]

In [51]:
options

[{'label': ID
  10008      Franchise Progression (Petroshius)
  10001                      Progressive (Long)
  10007          SSG Replay Franchise (Rotroff)
  10000                  Year-By-Year (Rotroff)
  10002                     24 Team (Strausler)
  10005               New Progression (DiPalma)
  10004                       Big Dawgs (Myers)
  10006            Random Association (Various)
  10013    Expansion Era Progression (Tonzillo)
  10003            Through the Ages (LeLacheur)
  10012            Win Place Show League (Lang)
  10010      Franchise Progression 2 (Sherwood)
  10011       Quick Franchise Decade (Sherwood)
  10009        Franchise Progression (Sherwood)
  Name: Prog_Name, dtype: object, 'value': 'Prog_Name'}]

In [42]:
dfProgs

       ID                             Prog_Name
0   10008    Franchise Progression (Petroshius)
1   10001                    Progressive (Long)
2   10007        SSG Replay Franchise (Rotroff)
3   10000                Year-By-Year (Rotroff)
4   10002                   24 Team (Strausler)
5   10005             New Progression (DiPalma)
6   10004                     Big Dawgs (Myers)
7   10006          Random Association (Various)
8   10013  Expansion Era Progression (Tonzillo)
9   10003          Through the Ages (LeLacheur)
10  10012          Win Place Show League (Lang)
11  10010    Franchise Progression 2 (Sherwood)
12  10011     Quick Franchise Decade (Sherwood)
13  10009      Franchise Progression (Sherwood)

In [46]:
progressions = dfProgs.set_index('ID')

In [47]:
progressions

                                  Prog_Name
ID
10008    Franchise Progression (Petroshius)
10001                    Progressive (Long)
10007        SSG Replay Franchise (Rotroff)
10000                Year-By-Year (Rotroff)
10002                   24 Team (Strausler)
10005             New Progression (DiPalma)
10004                     Big Dawgs (Myers)
10006          Random Association (Various)
10013  Expansion Era Progression (Tonzillo)
10003          Through the Ages (LeLacheur)
10012          Win Place Show League (Lang)
10010    Franchise Progression 2 (Sherwood)
10011     Quick Franchise Decade (Sherwood)
10009      Franchise Progression (Sherwood)

In [52]:
dfProgLeagues = pd.read_sql_table('v_prog_league_list', mysqlEngine)

In [54]:
dfProgLeagues = dfProgLeagues.set_index('CurTeam')
dfProgLeagues

,Prog_ID,Prog_Name,League_Name
CurTeam,,,
98C2AWSF3UBKV8ZVM8JQ,10002,24 Team (Strausler),24 Team Progression - 1999
WXKR7ZQWVHN5WEPJR5U5,10002,24 Team (Strausler),24 Team Progression - 1998
WY59SXATSHBBVS26DPGR,10002,24 Team (Strausler),24 Team Progression - 1997
KCACK7BVZ8AM8MBBA8SZ,10002,24 Team (Strausler),24 Team Progression - 1996
T444TC88RFMTY8PZ7JCW,10002,24 Team (Strausler),24 Team Progression - 1995
Z4A9TDYHSHJQKTETUVTA,10002,24 Team (Strausler),24 Team Progression - 1994
LS73SWW5SFY3GXSJMHD5,10002,24 Team (Strausler),24 Team Progression - 1993
HZ2Z2CEXV7QSES9T9LWY,10002,24 Team (Strausler),24 Team Progression - 1992
4ZES9NFV48GGN7QCB8ZP,10002,24 Team (Strausler),24 Team Progression - 1991
CL8YTZ2FKEVRRG6AUM9M,10002,24 Team (Strausler),24 Team Progression - 1990
MXHWC3V36TVC8PNGQ9QF,10002,24 Team (Strausler),24 Team Progression - 1989
KGUD9CTEHS8NLGKJCSQC,10002,24 Team (Strausler),24 team progression- 1988
793ENDJMSBJAQH36ZE9N,10002,24 Team (Strausler),24 team progression- 1987
79Q33U77R76W7CNZ7REC,10002,24 Team (Strausler),24 team progression- 1986
TUB5WERMXQ69XCE9G9CN,10002,24 Team (Strausler),24 team progression- 1985
GK9ZS6JB3CYS3XL5R65X,10002,24 Team (Strausler),24 team progression- 1984
ZXDB79BY25Z38GKATYR6,10002,24 Team (Strausler),24 team progression- 1983
E6WUE3R5J7ZYVBZ8WCXB,10002,24 Team (Strausler),24 team progression- 1982
PJQRP7NE5UVYR896QEGX,10002,24 Team (Strausler),24 team progression- 1981
4DSMWE8XSS8PMECMXMQE,10002,24 Team (Strausler),24 team progression - 1980
5Z6VNY29YAGBDT3BSYZ2,10002,24 Team (Strausler),24 Team Progression - 1979
3CYCP88ZR2Z2NH2RHUSW,10002,24 Team (Strausler),24 team progression- 1978
J48XKH46LULP5C5RJ4HR,10002,24 Team (Strausler),24 team progression- 1976
RZL2CQPKPAVL69QFMSFF,10004,Big Dawgs (Myers),Big Dawgs Finale 2014-19
8K53SJNQRZEV7RPHGBP2,10004,Big Dawgs (Myers),Big Dawgs 2009-2013
7WMDN44XYWTG2946DE2Z,10004,Big Dawgs (Myers),Big Dawgs 2006-08
2S466RR9HTEFZHECB7QA,10004,Big Dawgs (Myers),Big Dawgs 2000-05
9FB9D4MQR4LDP5EY9FMP,10004,Big Dawgs (Myers),Big Dawgs 1997-99
JW7YGG6659CEAGAP4WUT,10004,Big Dawgs (Myers),Big Dawgs 1993-96
NKMYW3E9V9WM5E6WL8Z6,10004,Big Dawgs (Myers),Big Dawgs 1988-92
...,...,...,...
4PE6KFHD4XAPS5ZFJ7CQ,10003,Through the Ages (LeLacheur),Through the Ages: 1928
GQUNKK8JNSDW9DCJ2J9F,10003,Through the Ages (LeLacheur),Through the Ages: 1927
RMMPJSEQA8RP5HA9UP27,10003,Through the Ages (LeLacheur),Through the Ages: 1926
XF7RNWVG34SUAM3PLZHZ,10012,Win Place Show League (Lang),Win Place Show League 6
PR7EEARMDL42RKEYMUEH,10012,Win Place Show League (Lang),Win Place Show League 5
4KC6JA7CW6TXEACND6H2,10012,Win Place Show League (Lang),Win Place Show League 4
5DRMVL62SSBSNSQ8X8GF,10012,Win Place Show League (Lang),Win Place Show League #3
4EXDPFZ8PDTVCAPPKK9B,10012,Win Place Show League (Lang),Win Place Show League #2
KDSMKC5HBMUMRNYRMEYV,10012,Win Place Show League (Lang),Win Place Show League #1
E7EH6QL4Y64GYX7LZXF6,10000,Year-By-Year (Rotroff),1982 Year-By-Year Progression
UVEV5YH78K96XCHZUWJA,10000,Year-By-Year (Rotroff),1981 Year-By-Year Progression
BYFPNV2EXDVCQEFPXBC3,10000,Year-By-Year (Rotroff),1980 Year-By-Year Progression
2N2XCD7ACZ7X4RU59CW6,10000,Year-By-Year (Rotroff),1979 Year-By-Year Progression
BG6RTBAT74YK3JFM477W,10000,Year-By-Year (Rotroff),1978 Year-By-Year Progression
PUW5DF4F7YH295J4WZU3,10000,Year-By-Year (Rotroff),1977 Year-By-Year Progression
X6TJH78EH4XB29NL6R65,10000,Year-By-Year (Rotroff),1976 Year-By-Year Progression
NL7RRE63TEX8FXB4775D,10000,Year-By-Year (Rotroff),1975 Year-By-Year Progression
9VC7MA845SCBYDQBMKHK,10000,Year-By-Year (Rotroff),1974 Year-By-Year League
EGKVJJWNF83UBNR42ZJ2,10000,Year-By-Year (Rotroff),1973 Year-By-Year League
P2MJSPMBBSN9DFAFSCU6,10000,Year-By-Year (Rotroff),1972 Year-By-Year League
5FWS2M7UPPFJ58A2MCWQ,10000,Year-By-Year (Rotroff),1971 Year-By-Year League
42LB6VV7Q3WDDEFT2TL2,10000,Year-By-Year (Rotroff),1970 Year-By-Year League
GLBZ6N3X955UEG3HTBVW,10000,Year-By-Year (Rotroff),1969 Year-by-Year League
A8FUBLNN6A6CQJQ73DMC,10000,Year-By-Year (Rotroff),1968 Year-by-Year League
5ALVRT5S9NF666MNP7ZR,10000,Year-By-Year (Rotroff),1967 Year-by-Year League
QFM4N2URZUHSR9YK2GJG,10000,Year-By-Year (Rotroff),1966 Year-by-Year League
MB9B3L7DKU9GKH2NXNUQ,10000,Year-By-Year (Rotroff),1965 Year-by-Year League
8E6X2R9FADJTA6YVS55Y,10000,Year-By-Year (Rotroff),1964 Year-by-Year League
F49D2GSRGC8F2XJ7YP2W,10000,Year-By-Year (Rotroff),1963 Year-by-Year League
GWKPM7XS5CAEYP3X6XT9,10000,Year-By-Year (Rotroff),1962 Year-by-Year League

In [57]:
dfProgs = pd.read_sql_table('v_prog_list', mysqlEngine) 
progressions = dfProgs.set_index('ID').squeeze().to_dict()
progressions

{10008: 'Franchise Progression (Petroshius)',
 10001: 'Progressive (Long)',
 10007: 'SSG Replay Franchise (Rotroff)',
 10000: 'Year-By-Year (Rotroff)',
 10002: '24 Team (Strausler)',
 10005: 'New Progression (DiPalma)',
 10004: 'Big Dawgs (Myers)',
 10006: 'Random Association (Various)',
 10013: 'Expansion Era Progression (Tonzillo)',
 10003: 'Through the Ages (LeLacheur)',
 10012: 'Win Place Show League (Lang)',
 10010: 'Franchise Progression 2 (Sherwood)',
 10011: 'Quick Franchise Decade (Sherwood)',
 10009: 'Franchise Progression (Sherwood)'}

In [58]:
options=[{'label': v, 'value': k} for k, v in progressions.items()]
options

[{'label': 'Franchise Progression (Petroshius)', 'value': 10008},
 {'label': 'Progressive (Long)', 'value': 10001},
 {'label': 'SSG Replay Franchise (Rotroff)', 'value': 10007},
 {'label': 'Year-By-Year (Rotroff)', 'value': 10000},
 {'label': '24 Team (Strausler)', 'value': 10002},
 {'label': 'New Progression (DiPalma)', 'value': 10005},
 {'label': 'Big Dawgs (Myers)', 'value': 10004},
 {'label': 'Random Association (Various)', 'value': 10006},
 {'label': 'Expansion Era Progression (Tonzillo)', 'value': 10013},
 {'label': 'Through the Ages (LeLacheur)', 'value': 10003},
 {'label': 'Win Place Show League (Lang)', 'value': 10012},
 {'label': 'Franchise Progression 2 (Sherwood)', 'value': 10010},
 {'label': 'Quick Franchise Decade (Sherwood)', 'value': 10011},
 {'label': 'Franchise Progression (Sherwood)', 'value': 10009}]

In [69]:
dfProgLeagues = pd.read_sql_table('v_prog_league_list', mysqlEngine)
selected_prog = 10005
dffProgLeagues = dfProgLeagues[dfProgLeagues['Prog_ID'] == selected_prog]
dffProgLeagues = dffProgLeagues.drop('Prog_ID', axis=1)
dffProgLeagues

                 CurTeam           League_Name
64  WEEL4SNKL2LT7965LXNU  New Progression 1956
65  46FGGMKK47A4NTL9LNLF  New Progression 1955
66  W4J4RVXYPH3VUC6FECLC  New Progression 1954
67  R86RLQ2HERYR6PN72JEV  New Progression 1953
68  88M8QVRBX68WV57XB6SZ  New Progression 1952
69  ABBB3F9N68RXX24LMDNQ  New Progression 1951
70  M4HXRBP33UU73TSFM8XD  New Progression 1950
71  9LSH7WC9K3T5P9SPZM6N  New Progression 1949
72  GVPH2LRU36YHNDAQTER4  New Progression 1948
73  JSZYPNZERRMUDPC72272  New Progression 1947

In [70]:
leagues = dffProgLeagues.set_index('CurTeam').squeeze().to_dict()
leagues

{'WEEL4SNKL2LT7965LXNU': 'New Progression 1956',
 '46FGGMKK47A4NTL9LNLF': 'New Progression 1955',
 'W4J4RVXYPH3VUC6FECLC': 'New Progression 1954',
 'R86RLQ2HERYR6PN72JEV': 'New Progression 1953',
 '88M8QVRBX68WV57XB6SZ': 'New Progression 1952',
 'ABBB3F9N68RXX24LMDNQ': 'New Progression 1951',
 'M4HXRBP33UU73TSFM8XD': 'New Progression 1950',
 '9LSH7WC9K3T5P9SPZM6N': 'New Progression 1949',
 'GVPH2LRU36YHNDAQTER4': 'New Progression 1948',
 'JSZYPNZERRMUDPC72272': 'New Progression 1947'}

In [64]:
options=[{'label': v, 'value': k} for i, k, v in leagues.items()]
options

[{'label': '24 Team Progression - 1999', 'value': '98C2AWSF3UBKV8ZVM8JQ'},
 {'label': '24 Team Progression - 1998', 'value': 'WXKR7ZQWVHN5WEPJR5U5'},
 {'label': '24 Team Progression - 1997', 'value': 'WY59SXATSHBBVS26DPGR'},
 {'label': '24 Team Progression - 1996', 'value': 'KCACK7BVZ8AM8MBBA8SZ'},
 {'label': '24 Team Progression - 1995', 'value': 'T444TC88RFMTY8PZ7JCW'},
 {'label': '24 Team Progression - 1994', 'value': 'Z4A9TDYHSHJQKTETUVTA'},
 {'label': '24 Team Progression - 1993', 'value': 'LS73SWW5SFY3GXSJMHD5'},
 {'label': '24 Team Progression - 1992', 'value': 'HZ2Z2CEXV7QSES9T9LWY'},
 {'label': '24 Team Progression - 1991', 'value': '4ZES9NFV48GGN7QCB8ZP'},
 {'label': '24 Team Progression - 1990', 'value': 'CL8YTZ2FKEVRRG6AUM9M'},
 {'label': '24 Team Progression - 1989', 'value': 'MXHWC3V36TVC8PNGQ9QF'},
 {'label': '24 team progression- 1988', 'value': 'KGUD9CTEHS8NLGKJCSQC'},
 {'label': '24 team progression- 1987', 'value': '793ENDJMSBJAQH36ZE9N'},
 {'label': '24 team progression- 1986', 'value': '79Q33U77R76W7CNZ7REC'},
 {'label': '24 team progression- 1985', 'value': 'TUB5WERMXQ69XCE9G9CN'},
 {'label': '24 team progression- 1984', 'value': 'GK9ZS6JB3CYS3XL5R65X'},
 {'label': '24 team progression- 1983', 'value': 'ZXDB79BY25Z38GKATYR6'},
 {'label': '24 team progression- 1982', 'value': 'E6WUE3R5J7ZYVBZ8WCXB'},
 {'label': '24 team progression- 1981', 'value': 'PJQRP7NE5UVYR896QEGX'},
 {'label': '24 team progression - 1980', 'value': '4DSMWE8XSS8PMECMXMQE'},
 {'label': '24 Team Progression - 1979', 'value': '5Z6VNY29YAGBDT3BSYZ2'},
 {'label': '24 team progression- 1978', 'value': '3CYCP88ZR2Z2NH2RHUSW'},
 {'label': '24 team progression- 1976', 'value': 'J48XKH46LULP5C5RJ4HR'},
 {'label': 'Big Dawgs Finale 2014-19', 'value': 'RZL2CQPKPAVL69QFMSFF'},
 {'label': 'Big Dawgs 2009-2013', 'value': '8K53SJNQRZEV7RPHGBP2'},
 {'label': 'Big Dawgs 2006-08', 'value': '7WMDN44XYWTG2946DE2Z'},
 {'label': 'Big Dawgs 2000-05', 'value': '2S466RR9HTEFZHECB7QA'},
 {'label': 'Big Dawgs 1997-99', 'value': '9FB9D4MQR4LDP5EY9FMP'},
 {'label': 'Big Dawgs 1993-96', 'value': 'JW7YGG6659CEAGAP4WUT'},
 {'label': 'Big Dawgs 1988-92', 'value': 'NKMYW3E9V9WM5E6WL8Z6'},
 {'label': 'Big Dawgs 1980-87', 'value': 'M3976H3JE9PBZK3ZDVXE'},
 {'label': 'Big Dawgs - Jack Cavin Memorial', 'value': 'R7UDL7TQ5ZRA6FGGZ7C3'},
 {'label': 'BIG DAWGS John Simon Memorial', 'value': 'KANRA8EBLSQB73L6ZYTR'},
 {'label': '1971 Expansion Era Progression', 'value': 'KJY6EGE7KE8VQSHFEZ42'},
 {'label': '1970 Expansion Era Progression', 'value': '7EB4QDT4E2M7U522BLKX'},
 {'label': '1969 Expansion Era Progression', 'value': 'LJLMREJS64UYKWKANWCV'},
 {'label': '1968 Expansion Era Progression', 'value': '38T8ZHG3WLNTXZ5JDBZU'},
 {'label': '1967 Expansion Era Progression', 'value': 'AAQ3R4RMU928RDRKW7XL'},
 {'label': '1966 Expansion Era Progression', 'value': 'EEJ2RWTM92LDENWL9GPM'},
 {'label': '1965 Expansion Era Progression', 'value': '29YJ59ZMLSU7UUUEFFSD'},
 {'label': '1964 Expansion Era Progression', 'value': 'DFRVGYCGRCEWMU6CENJV'},
 {'label': '1963 Expansion Era Progression', 'value': 'GCRKM2VZ3774K8T498W2'},
 {'label': '1962 Expansion Era Progression', 'value': 'W42PNFY6RYKY24CQPFTH'},
 {'label': "Franchise Progression '90-now", 'value': 'WZPMALSZQ5W7PFP3T85Z'},
 {'label': "Franchise Progression '80-'89", 'value': 'UE3MAXDH8M2HGUHAY9RM'},
 {'label': "Franchise Progression '70-'79", 'value': 'GM9RCP6ERHM6RXS49HDX'},
 {'label': "Franchise Progression '60-'69", 'value': 'B79EHZMH2KPRQD9JXAJ7'},
 {'label': "Franchise Progression '50-'59", 'value': 'XFDUUC877RL6ZWTNHS9A'},
 {'label': '1960s Franchise Progression SSG', 'value': 'US2PTPJQEX5SPMUQJZGW'},
 {'label': "Franchise Progression '40-'49", 'value': 'DBNU7JXE7ZCUZJX4XWW6'},
 {'label': '1950s Franchise Progression SSG', 'value': 'CT72PZQMH93D4RJKF3KG'},
 {'label': "Franchise Progression '30-'39", 'value': 'ETM28BT4325K9RP3YAJ2'},
 {'label': '1940s Franchise Progression SSG', 'value': 'DZKEVX3VCZYNZAA74XEL'},
 {'label': "Franchise Progression '20-'29", 'value': 'YJV9TZFJAW85K56TL8AJ'},
 {'label': "Franchise Progression 2 '90-now", 'value': 'QNDQNJTPJWC6ZYQGRZEU'},
 {'label': "Franchise Progression 2 '80-'89", 'value': 'DK47AHSHC9LQFKS3RF4U'},
 {'label': "Franchise Progression 2 '70-'79", 'value': 'SMRPRHCT9CDYDG8ZXY4G'},
 {'label': "Franchise Progression 2 '60-'69", 'value': '6MC2LTEUUYCMJVLM7LMV'},
 {'label': "Franchise Progression 2 '50-'59", 'value': '2PLE2SRE2US2S7TSRHWP'},
 {'label': "Franchise Progression 2 '40-'49", 'value': '8LGPGK5K6TRCJZGWH8YR'},
 {'label': "Franchise Progression 2 '30-'39", 'value': 'E9Z3VPW5NYQZ26QXKJK3'},
 {'label': "Franchise Progression 2 '20-'29", 'value': 'TY68Z3HD35Q4CHLSET7G'},
 {'label': "Franchise Progression 2 '10-'19", 'value': 'VHZ7K4WXFUXEDJDJVNQY'},
 {'label': "Franchise Progression 2 '01-'09", 'value': 'WBE9PQD78YFNNG8PN36M'},
 {'label': 'New Progression 1956', 'value': 'WEEL4SNKL2LT7965LXNU'},
 {'label': 'New Progression 1955', 'value': '46FGGMKK47A4NTL9LNLF'},
 {'label': 'New Progression 1954', 'value': 'W4J4RVXYPH3VUC6FECLC'},
 {'label': 'New Progression 1953', 'value': 'R86RLQ2HERYR6PN72JEV'},
 {'label': 'New Progression 1952', 'value': '88M8QVRBX68WV57XB6SZ'},
 {'label': 'New Progression 1951', 'value': 'ABBB3F9N68RXX24LMDNQ'},
 {'label': 'New Progression 1950', 'value': 'M4HXRBP33UU73TSFM8XD'},
 {'label': 'New Progression 1949', 'value': '9LSH7WC9K3T5P9SPZM6N'},
 {'label': 'New Progression 1948', 'value': 'GVPH2LRU36YHNDAQTER4'},
 {'label': 'New Progression 1947', 'value': 'JSZYPNZERRMUDPC72272'},
 {'label': '1998 Progressive League', 'value': 'BSY97XGJQH6RKNK6YDLW'},
 {'label': '1997 Progressive League', 'value': 'QZNJ7FH2AHQRU8FYXJ2E'},
 {'label': '1996 Progressive League', 'value': 'TR9FQK6EPB6DSBE6URN4'},
 {'label': '1995 Progressive League', 'value': 'AED7XQEJD2B4CM7UJM7Z'},
 {'label': '1994 Progressive League', 'value': '2QVTJRLEEJ2QFR8RPWD9'},
 {'label': '1993 Progressive League', 'value': 'MSYSGQYVWRTM8UXY25BG'},
 {'label': '1992 Progressive League', 'value': 'LBWE2E6KK5H8H9B2R7KR'},
 {'label': '1991 Progressive League', 'value': 'V2SGA5BH2D5VUKJVMUHD'},
 {'label': '1990 Progressive League', 'value': 'A29B6JE24MD8Q8HEKWBZ'},
 {'label': '1989 Progressive League', 'value': 'RLJFYE7BKRLSX9HT3HTW'},
 {'label': '1988 Progressive League', 'value': 'HDLUQQM7CA5HWG65WX66'},
 {'label': '1987 Progressive League', 'value': 'KB5GT3MSZJLC63KEZTTZ'},
 {'label': '1986 Progressive League', 'value': 'TK9SCSW2X3LEWPYD8EVK'},
 {'label': '1985 Progressive League', 'value': 'NGU4LLKTWGRPDK9C6RY9'},
 {'label': '1984 Progressive League', 'value': 'A8972NQUCMJG3RFXM42K'},
 {'label': '1983 Progressive League', 'value': '5VJ3GF5M92UPJZEW73MY'},
 {'label': '1982 Progressive League', 'value': 'MUV3FECKP3Q5Q8U7G784'},
 {'label': '1981 Progressive League', 'value': 'HU2HN2T48H2YCY6FMMXE'},
 {'label': '1980 Progressive League', 'value': 'HBH7VH8J3A5KYT7TKNYN'},
 {'label': "Quick Franchise Decade '90-now", 'value': 'WXXT9JW6JDHQYJQCZEV8'},
 {'label': "Quick Franchise Decade '80-'89", 'value': '3KC2ETAS3DQGZPKNKLN9'},
 {'label': "Quick Franchise Decade '70-'79", 'value': 'UYJAKP248VBE6B6VGP53'},
 {'label': "Quick Franchise Decade '60-'69", 'value': 'BRVM3KZX9JJA2GLD5CU5'},
 {'label': "Quick Franchise Decade '50-'59", 'value': '3RHHHTXR8ZCJPR56RGKE'},
 {'label': "Quick Franchise Decade '40-'49", 'value': 'LM46642JJKDJKLS4BA4U'},
 {'label': "Quick Franchise Decade '30-'39", 'value': 'GQS89WU77UMU5FKYT5BR'},
 {'label': "Quick Franchise Decade '20-'29", 'value': 'T42V5VWZQNRKZD4SLHAC'},
 {'label': "Quick Franchise Decade '10-'19", 'value': 'QLZHCW7JPZVEY9R9VCHH'},
 {'label': "Quick Franchise Decade '01-'09", 'value': 'J7SAPBZQ4PJ3JVF2UV7M'},
 {'label': 'RA600-30 Major League', 'value': 'JHHVVM776HVKSPPQ7MAC'},
 {'label': 'RA600-29 Major League', 'value': 'NFQ7T5DAKVRQTA8NC4QP'},
 {'label': 'RA600-28 AAAA League', 'value': 'CDG6479RSSWG7323H5T7'},
 {'label': 'RA600-27 AAAA League', 'value': 'C58QABEEM3WQ94RA7EHJ'},
 {'label': 'RA600-26 Major League', 'value': 'WQ73L9HLTW8GP72JJQDK'},
 {'label': 'RA600-25 AAA League', 'value': 'U64EF6MK2BT68RRJPE3D'},
 {'label': 'RA600-24 AAAA League', 'value': 'NS22N67LG7PRZZTBLBUL'},
 {'label': 'RA600-23 AAA League', 'value': 'S8M4BHR52Q9VQR6FYZ5B'},
 {'label': 'RA600-22 AAA League', 'value': 'W9K7KDDL3JDJZPC45GS9'},
 {'label': 'RA600-21 AAA League', 'value': 'MCR4KH77Q5LWH4YB9P7W'},
 {'label': 'RA600-20 Major League', 'value': 'ZTB29WRCT9C5X6E4XRHQ'},
 {'label': 'RA600-19 AAA League', 'value': 'CKKSXGFM7F62LYKVWWGM'},
 {'label': 'RA600-18 AAAA League', 'value': 'H3RCSBLVH5URZHSMY5UG'},
 {'label': 'RA600-17 AAAA League', 'value': 'XPEX8LE85CQR7SYMGV6Y'},
 {'label': 'RA600-16 AAAA League', 'value': 'Z86HPYFSC3CC9YZTP8EF'},
 {'label': 'RA600-15 Major League', 'value': 'W3JNF3YEBQ9LD3KQJQX7'},
 {'label': 'RA600-14 Major League', 'value': 'FMJ9NY7MKHKMKWC9XKNX'},
 {'label': 'RA600-13 AAAA League', 'value': 'FZG99X36A76TW3VFVRRU'},
 {'label': 'RA600-12 AAAA League', 'value': 'TAZBAUQVBX7WG7MDKH5W'},
 {'label': 'RA600-11 AAAA League', 'value': 'FQGHTWAYN9LB7L55TBTV'},
 {'label': 'RA600-10 Major League', 'value': '6ZWH2YHEVUMH4M8HU6LB'},
 {'label': 'RA600-9 AAA League', 'value': 'PXYWJT46NGLSWPCCVVXT'},
 {'label': 'RA600-8 AAAA League', 'value': 'FR67VSVE7A34KL75FNSU'},
 {'label': 'RA600-7 AAA League', 'value': '2RRXB2Z3Q4W22ZQDD868'},
 {'label': 'RA600-6 Major League', 'value': 'Z5FQ2BSEZXAC6K7Q4VYQ'},
 {'label': 'RA600-5 Major League', 'value': 'DWDYXRG5G2TGCNM8E2XB'},
 {'label': 'RA600-4 AAA League', 'value': 'HX67R5KMSLCDFBBTRYVH'},
 {'label': 'RA600-3 AAA League', 'value': '3XFZ3Y4MBPRSLRTYXR62'},
 {'label': 'RA600-2 AAAA League', 'value': '2YEHTBD8AEVQH5JXFAC8'},
 {'label': 'RC600-1 AAA League', 'value': '6ES6PZN7TW5VH2XK8MWC'},
 {'label': 'SSG 2004 Replay', 'value': 'N4895RDZ7NNMNMNNNKF2'},
 {'label': 'SSG 2003 Replay', 'value': 'TME44YGWDMKBVGR2UBWM'},
 {'label': 'SSG 2002 Replay', 'value': 'A28BFQBU54PWFY98CMMF'},
 {'label': 'SSG 2001 Replay', 'value': 'BRSX649FGKE6GFZUSK5P'},
 {'label': 'SSG 2000 Replay', 'value': 'YLVZTPYYZ7WA4RKGA7M5'},
 {'label': 'SSG 1999 Replay', 'value': '4X9DK3W3HWB7WUBYNQS9'},
 {'label': 'SSG 1998 Replay', 'value': 'P9S4PQMSK87Z4RTLR9MS'},
 {'label': 'SSG 1997 Replay', 'value': 'HRC9CAVFCSPEAZPHJKFK'},
 {'label': 'SSG 1996 Replay', 'value': '36Y7GU8FB92U3S6EQDH2'},
 {'label': 'SSG 1995 Replay', 'value': 'CQXLTQSJLX3SZ7JWCF8J'},
 {'label': 'SSG 1993 Replay', 'value': '8TLUGRT6CJYJNELZUWLE'},
 {'label': 'SSG 1992 Replay', 'value': 'K7LBDGBAHDHGJYJ4MF3F'},
 {'label': 'SSG 1991 Replay', 'value': 'KBG9JJ5PHA8MLH59NABM'},
 {'label': 'SSG 1990 Replay', 'value': 'B6E47JVXUTL9SPT59FTW'},
 {'label': 'SSG 1989 Replay', 'value': '45YBDK3VX46UJGTY5SXE'},
 {'label': 'SSG 1988 Replay', 'value': 'HYHL4YPKWWY6XBGLLWGZ'},
 {'label': 'SSG 1987 Replay', 'value': '5KEDTW4GZ3AZLZ822JTE'},
 {'label': 'SSG 1986 Replay', 'value': '2ZA2GNPHSC4PH85Z4AUF'},
 {'label': 'SSG 1985 Replay', 'value': 'KXG9S6LERDDLZN3TJZSG'},
 {'label': 'SSG 1984 Replay', 'value': '2SZB9H39S7YQEBBX4XPF'},
 {'label': 'SSG 1983 Replay', 'value': 'BN7MFCGLUSURAWSKZDQW'},
 {'label': 'SSG 1982 Replay', 'value': 'ZZTBDPKA9V568KKKH9MA'},
 {'label': 'Single Season Game 1981 Replay', 'value': 'PL9RVKXU482J3CEGPLER'},
 {'label': 'Through the Ages: 1939', 'value': '8K9LGZYBUNBQ62P87ZGD'},
 {'label': 'Through the Ages: 1938', 'value': 'JTA5DL86E5BL8FUU6ENG'},
 {'label': 'Through the Ages: 1937', 'value': 'C9JABJSUQRTLCA6H23PR'},
 {'label': 'Through the Ages: 1936', 'value': 'FK7792TCZ23RP2QE8HM4'},
 {'label': 'Through the Ages: 1935', 'value': 'QFTK5Q3R7DF6JS82AKGW'},
 {'label': 'Through the Ages: 1934', 'value': '446UKDGK6RSUW8978USR'},
 {'label': 'Through the Ages: 1933', 'value': '64XDRMXLDDB7RX3AM3M4'},
 {'label': 'Through the Ages: 1932', 'value': 'SNLAVSXJHLQERCQ7ZAMM'},
 {'label': 'Through the Ages: 1931', 'value': '7KTXYN5TMR3BEJTSUZXT'},
 {'label': 'Through the Ages: 1930', 'value': 'RBGMNDRLCKDGGETDFYNL'},
 {'label': 'Through the Ages: 1929', 'value': 'JL39P8C84PMAUFWFC7K9'},
 {'label': 'Through the Ages: 1928', 'value': '4PE6KFHD4XAPS5ZFJ7CQ'},
 {'label': 'Through the Ages: 1927', 'value': 'GQUNKK8JNSDW9DCJ2J9F'},
 {'label': 'Through the Ages: 1926', 'value': 'RMMPJSEQA8RP5HA9UP27'},
 {'label': 'Win Place Show League 6', 'value': 'XF7RNWVG34SUAM3PLZHZ'},
 {'label': 'Win Place Show League 5', 'value': 'PR7EEARMDL42RKEYMUEH'},
 {'label': 'Win Place Show League 4', 'value': '4KC6JA7CW6TXEACND6H2'},
 {'label': 'Win Place Show League #3', 'value': '5DRMVL62SSBSNSQ8X8GF'},
 {'label': 'Win Place Show League #2', 'value': '4EXDPFZ8PDTVCAPPKK9B'},
 {'label': 'Win Place Show League #1', 'value': 'KDSMKC5HBMUMRNYRMEYV'},
 {'label': '1982 Year-By-Year Progression', 'value': 'E7EH6QL4Y64GYX7LZXF6'},
 {'label': '1981 Year-By-Year Progression', 'value': 'UVEV5YH78K96XCHZUWJA'},
 {'label': '1980 Year-By-Year Progression', 'value': 'BYFPNV2EXDVCQEFPXBC3'},
 {'label': '1979 Year-By-Year Progression', 'value': '2N2XCD7ACZ7X4RU59CW6'},
 {'label': '1978 Year-By-Year Progression', 'value': 'BG6RTBAT74YK3JFM477W'},
 {'label': '1977 Year-By-Year Progression', 'value': 'PUW5DF4F7YH295J4WZU3'},
 {'label': '1976 Year-By-Year Progression', 'value': 'X6TJH78EH4XB29NL6R65'},
 {'label': '1975 Year-By-Year Progression', 'value': 'NL7RRE63TEX8FXB4775D'},
 {'label': '1974 Year-By-Year League', 'value': '9VC7MA845SCBYDQBMKHK'},
 {'label': '1973 Year-By-Year League', 'value': 'EGKVJJWNF83UBNR42ZJ2'},
 {'label': '1972 Year-By-Year League', 'value': 'P2MJSPMBBSN9DFAFSCU6'},
 {'label': '1971 Year-By-Year League', 'value': '5FWS2M7UPPFJ58A2MCWQ'},
 {'label': '1970 Year-By-Year League', 'value': '42LB6VV7Q3WDDEFT2TL2'},
 {'label': '1969 Year-by-Year League', 'value': 'GLBZ6N3X955UEG3HTBVW'},
 {'label': '1968 Year-by-Year League', 'value': 'A8FUBLNN6A6CQJQ73DMC'},
 {'label': '1967 Year-by-Year League', 'value': '5ALVRT5S9NF666MNP7ZR'},
 {'label': '1966 Year-by-Year League', 'value': 'QFM4N2URZUHSR9YK2GJG'},
 {'label': '1965 Year-by-Year League', 'value': 'MB9B3L7DKU9GKH2NXNUQ'},
 {'label': '1964 Year-by-Year League', 'value': '8E6X2R9FADJTA6YVS55Y'},
 {'label': '1963 Year-by-Year League', 'value': 'F49D2GSRGC8F2XJ7YP2W'},
 {'label': '1962 Year-by-Year League', 'value': 'GWKPM7XS5CAEYP3X6XT9'}]

In [73]:
dfProgTeams = pd.read_sql_table('v_prog_team_list', mysqlEngine) 
selected_league = 'WEEL4SNKL2LT7965LXNU'
dffProgTeams = dfProgTeams[dfProgTeams['CurTeam'] == selected_league]
dffProgTeams = dffProgTeams.drop('CurTeam', axis=1)
dffProgTeams

,Team_Link,Team_Name
2496,C2EE21FC0EE835AACF99276B97A7E668,1956 Cambridgeport Reds (Hickey)
2497,C2EE21FC0EE835AA5098918A6F6CDBC3,1956 Camp Columbia Buffleheads (camphenn)
2498,AE13E7A0C4EBFAFC961FE8CB3C2D37B9,56 Hillbilly Porn Stars (Wheat4)
2499,3670F0BEDB22714D617AFFF85AA60DA4,56 Problems (RDogg)
2500,AE13E7A0C4EBFAFC5E14E1EA81438FBA,56' (bsayball3)
2501,C2EE21FC0EE835AAB939C2062DD94562,Brooklyn Blues '56 (tomcat)
2502,85B1B15F129AFC61EC0FA41FE59DF5FE,Detour 1956 (steffens)
2503,AE13E7A0C4EBFAFCB439B39060F296DA,L.A. Blue Sox '56 (BKinLA)
2504,C2EE21FC0EE835AA53E58F3FC0A3AD27,New York Knights (Patchguy)
2505,448A833DA64C5E9BF32237E9C7524F5F,trina 1956 (wkinsell)
2506,448A833DA64C5E9B93C78E4B2AB89D65,Washington Nats 1956 (GK306)
2507,448A833DA64C5E9BA34C21CDC9707DEE,Wausau Lumberjacks (mdipalma78)

In [75]:
teams = dffProgTeams.set_index('Team_Link').squeeze().to_dict()
teams

{'C2EE21FC0EE835AACF99276B97A7E668': '1956 Cambridgeport Reds (Hickey)',
 'C2EE21FC0EE835AA5098918A6F6CDBC3': '1956 Camp Columbia Buffleheads (camphenn)',
 'AE13E7A0C4EBFAFC961FE8CB3C2D37B9': '56 Hillbilly Porn Stars (Wheat4)',
 '3670F0BEDB22714D617AFFF85AA60DA4': '56 Problems (RDogg)',
 'AE13E7A0C4EBFAFC5E14E1EA81438FBA': "56' (bsayball3)",
 'C2EE21FC0EE835AAB939C2062DD94562': "Brooklyn Blues '56 (tomcat)",
 '85B1B15F129AFC61EC0FA41FE59DF5FE': 'Detour 1956 (steffens)',
 'AE13E7A0C4EBFAFCB439B39060F296DA': "L.A. Blue Sox '56 (BKinLA)",
 'C2EE21FC0EE835AA53E58F3FC0A3AD27': 'New York Knights (Patchguy)',
 '448A833DA64C5E9BF32237E9C7524F5F': 'trina 1956 (wkinsell)',
 '448A833DA64C5E9B93C78E4B2AB89D65': 'Washington Nats 1956 (GK306)',
 '448A833DA64C5E9BA34C21CDC9707DEE': 'Wausau Lumberjacks (mdipalma78)'}

In [77]:
options=[{'label': v, 'value': k} for k, v in teams.items()]
options

[{'label': '1956 Cambridgeport Reds (Hickey)',
  'value': 'C2EE21FC0EE835AACF99276B97A7E668'},
 {'label': '1956 Camp Columbia Buffleheads (camphenn)',
  'value': 'C2EE21FC0EE835AA5098918A6F6CDBC3'},
 {'label': '56 Hillbilly Porn Stars (Wheat4)',
  'value': 'AE13E7A0C4EBFAFC961FE8CB3C2D37B9'},
 {'label': '56 Problems (RDogg)', 'value': '3670F0BEDB22714D617AFFF85AA60DA4'},
 {'label': "56' (bsayball3)", 'value': 'AE13E7A0C4EBFAFC5E14E1EA81438FBA'},
 {'label': "Brooklyn Blues '56 (tomcat)",
  'value': 'C2EE21FC0EE835AAB939C2062DD94562'},
 {'label': 'Detour 1956 (steffens)',
  'value': '85B1B15F129AFC61EC0FA41FE59DF5FE'},
 {'label': "L.A. Blue Sox '56 (BKinLA)",
  'value': 'AE13E7A0C4EBFAFCB439B39060F296DA'},
 {'label': 'New York Knights (Patchguy)',
  'value': 'C2EE21FC0EE835AA53E58F3FC0A3AD27'},
 {'label': 'trina 1956 (wkinsell)',
  'value': '448A833DA64C5E9BF32237E9C7524F5F'},
 {'label': 'Washington Nats 1956 (GK306)',
  'value': '448A833DA64C5E9B93C78E4B2AB89D65'},
 {'label': 'Wausau Lumberjacks (mdipalma78)',
  'value': '448A833DA64C5E9BA34C21CDC9707DEE'}]

In [78]:
dfHitters = pd.read_sql_table('v_hitroster', mysqlEngine) 
selected_team = '448A833DA64C5E9BA34C21CDC9707DEE'
dffHitters = dfHitters[dfHitters['Team_Link'] == selected_team]
dffHitters

Empty DataFrame
Columns: [ID, CurTeam, Team_Link, Player, Salary, Pos, B_T, Season, playerID, Injury, PA, AVG, OBP, SLG, OPS, Clutch, RC650, RC6, BS, BH, R, S, J, L_Avg, L_OBP, L_SLG, L_OPS, L_RC600, L_PA, L_2B_600, L_3B_600, L_HR_600, L_BB_600, R_Avg, R_OBP, R_SLG, R_OPS, R_RC600, R_PA, R_2B_600, R_3B_600, R_HR_600, R_BB_600, C_E, C_R, C_PB, C_Th, 1B_E, 1B_R, 2B_E, 2B_R, 3B_E, 3B_R, SS_E, SS_R, LF_E, LF_R, CF_E, CF_R, RF_E, RF_R, OF_T, $/PA, futWAR, ContWar, NPWAR, CurrWAR]
Index: []

[0 rows x 67 columns]

In [72]:
dffHitters = dfHitters[dfHitters['Team_Link'] == selected_team]

,ID,CurTeam,Team_Link,Player,Salary,Pos,B_T,Season,playerID,Injury,...,CF_E,CF_R,RF_E,RF_R,OF_T,$/PA,futWAR,ContWar,NPWAR,CurrWAR
0,86922,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Bannister, Alan","$2,238,000","2B, SS, LF, CF, RF",R,1982,bannial01,2,...,69.0,3.0,69.0,3.0,3.0,4680.904523,1.24,1.24,0.46875,1.25
1,86919,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Butera, Sal","$777,000",C,R,1982,butersa01,1,...,NaN,NaN,NaN,NaN,NaN,2753.424658,-2.10,-2.10,-0.17175,-0.22
2,86931,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Castillo, Carmen","$589,000","RF, LF, CF",R,1982,castica01,1,...,111.0,2.0,111.0,2.0,3.0,1658.914729,-1.22,-1.22,0.18100,-0.33
3,86921,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Cooper, Cecil","$11,768,000",1B,L,1982,coopece01,1,...,NaN,NaN,NaN,NaN,NaN,16369.252874,10.30,10.30,3.38700,5.63
4,86924,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"DeCinces, Doug","$13,638,000","3B, SS",R,1982,decindo01,1,...,NaN,NaN,NaN,NaN,NaN,20248.854962,18.85,18.85,4.54725,7.58
5,86926,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Downing, Brian","$10,066,000",LF,R,1982,downibr01,1,...,NaN,NaN,NaN,NaN,3.0,13366.896552,33.61,33.61,3.72700,5.59
6,86932,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Guerrero, Pedro","$14,870,000","RF, 3B, CF",R,1982,guerrpe01,1,...,113.0,3.0,113.0,2.0,4.0,22231.595092,30.04,30.04,5.37175,6.77
7,86929,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Hall, Mel","$778,000",CF,L,1982,hallme01,1,...,146.0,4.0,NaN,NaN,3.0,4579.545455,8.85,9.20,0.89350,-0.30
8,86933,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Hammond, Steve","$500,000","RF, LF",L,1982,hammost01,1,...,NaN,NaN,58.0,2.0,2.0,954.198473,-0.26,-0.26,-0.10400,-0.26
9,86927,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Harper, Brian","$822,000",LF,R,1982,harpebr01,1,...,NaN,NaN,NaN,NaN,3.0,14419.354839,12.41,12.41,0.04725,0.20
10,86930,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Howard, Mike","$500,000","CF, 2B, LF, RF",S,1982,howarmi01,1,...,86.0,3.0,86.0,3.0,3.0,2604.166667,0.04,0.04,0.02650,0.10
11,86934,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Jackson, Reggie","$8,570,000",RF,L,1982,jacksre01,1,...,NaN,NaN,164.0,5.0,5.0,13196.457327,3.10,3.10,1.04300,3.12
12,86925,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Johnson, Howard","$2,250,000","3B, LF, RF",S,1982,johnsho01,1,...,NaN,NaN,94.0,3.0,3.0,10838.150289,22.20,22.20,0.72775,0.94
13,86923,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Little, Bryan","$504,000","2B, SS",S,1982,littlbr01,1,...,NaN,NaN,NaN,NaN,NaN,2744.680851,1.81,1.81,0.22325,-0.46
14,86920,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Parrish, Lance","$11,203,000",C,R,1982,parrila02,1,...,NaN,NaN,NaN,NaN,NaN,20468.809074,28.91,28.91,4.27950,5.04
15,86928,E7EH6QL4Y64GYX7LZXF6,2624080F263FE6FA7D0A02E73F171419,"Raines, Tim","$6,192,000","LF, 2B",S,1982,raineti01,1,...,NaN,NaN,NaN,NaN,1.0,7957.592339,66.01,65.46,4.95950,2.80
16,87003,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Bando, Chris","$696,000","C, 3B",S,1982,bandoch01,2,...,NaN,NaN,NaN,NaN,NaN,1514.150943,1.75,1.75,0.52000,0.17
17,87011,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Biancalana, Buddy","$501,000",SS,S,1982,biancbu01,1,...,NaN,NaN,NaN,NaN,NaN,42000.000000,-1.64,-1.64,-0.03950,0.22
18,87009,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Braun, Steve","$886,000","3B, LF, RF",L,1982,braunst01,2,...,NaN,NaN,98.0,4.0,3.0,7000.000000,1.10,1.10,0.19725,-0.01
19,87010,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Brett, George","$10,736,000","3B, LF",L,1982,brettge01,1,...,NaN,NaN,NaN,NaN,2.0,16472.178060,39.76,39.76,5.18925,5.99
20,87005,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Buckner, Bill","$8,834,000",1B,L,1982,bucknbi01,0,...,NaN,NaN,NaN,NaN,NaN,11930.888575,1.85,1.85,1.82700,3.67
21,87028,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Capra, Nick","$500,000","LF, CF, RF",R,1982,caprani01,1,...,93.0,3.0,93.0,3.0,3.0,6578.947368,-0.10,0.19,0.08475,0.29
22,87013,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Foster, George","$2,811,000",LF,R,1982,fostege01,1,...,NaN,NaN,NaN,NaN,4.0,4006.578947,4.47,4.47,0.58600,-0.57
23,87017,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Gamble, Oscar","$6,031,000","DH, LF, RF",L,1982,gamblos01,1,...,NaN,NaN,68.0,3.0,5.0,14806.282723,3.22,3.22,1.19850,2.66
24,87004,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Kennedy, Terry","$8,359,000","C, 1B",L,1982,kennete02,1,...,NaN,NaN,NaN,NaN,NaN,13218.543046,19.35,19.35,3.43675,4.57
25,87006,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Milner, John","$532,000",1B,L,1982,milnejo01,2,...,NaN,NaN,NaN,NaN,NaN,2415.384615,-0.11,-0.11,-0.04400,-0.11
26,87029,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Ortiz, Junior","$500,000",C,R,1982,ortizju01,1,...,NaN,NaN,NaN,NaN,NaN,7812.500000,-0.30,-0.30,-0.30575,-0.06
27,87007,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Phillips, Mike","$500,000","2B, SS",L,1982,phillmi01,1,...,NaN,NaN,NaN,NaN,NaN,13888.888889,-0.27,-0.27,-0.07650,-0.09
28,87016,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Puhl, Terry","$5,738,000","RF, CF",L,1982,puhlte01,1,...,53.0,4.0,53.0,2.0,4.0,9458.553792,11.91,11.91,1.82200,1.02
29,87014,E7EH6QL4Y64GYX7LZXF6,3EAF5FB809DA07BB0E23DA1FD8E3579D,"Smith, Lonnie","$9,715,000","LF, CF",R,1982,smithlo01,1,...,128.0,3.0,NaN,NaN,1.0,13898.809524,34.23,34.23,3.90700,6.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,86983,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Bosley, Thad","$500,000","LF, CF, RF",L,1982,bosleth01,1,...,94.0,4.0,94.0,4.0,4.0,2500.000000,1.84,1.84,0.10700,-0.91
164,86985,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Clark, Bob","$637,000","CF, LF, RF",R,1982,clarkbo04,1,...,56.0,3.0,56.0,2.0,3.0,2817.204301,-1.70,-1.70,-0.36675,-0.41
165,86982,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Concepcion, Onix","$828,000","SS, 2B",R,1982,conceon01,2,...,NaN,NaN,NaN,NaN,NaN,2106.976744,0.47,0.42,-0.01250,-0.42
166,86979,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Flynn, Doug","$528,000","2B, SS",R,1982,flynndo01,1,...,NaN,NaN,NaN,NaN,NaN,315.463918,-4.22,-4.22,-1.28675,-2.47
167,87002,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Franco, Julio","$575,000","SS, 3B",R,1982,francju01,1,...,NaN,NaN,NaN,NaN,NaN,6250.000000,43.54,36.94,1.03350,-0.09
168,86986,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Green, David","$1,526,000","CF, LF, RF",R,1982,greenda03,2,...,44.0,3.0,44.0,3.0,2.0,6466.292135,4.09,3.94,1.07275,1.17
169,86984,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Hatcher, Mickey","$1,108,000","LF, 3B, CF, RF",R,1982,hatchmi01,1,...,85.0,4.0,85.0,4.0,3.0,2562.937063,4.04,4.04,0.49425,-1.62
170,86977,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Hebner, Richie","$3,073,000","1B, 3B, RF",L,1982,hebneri01,1,...,NaN,NaN,110.0,4.0,3.0,9601.423488,2.15,2.15,0.78000,1.63
171,86981,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Lansford, Carney","$4,092,000",3B,R,1982,lansfca01,2,...,NaN,NaN,NaN,NaN,NaN,6896.103896,29.62,29.62,2.59200,2.32
172,86988,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Parrish, Larry","$3,902,000","RF, 3B",R,1982,parrila01,1,...,NaN,NaN,217.0,5.0,3.0,7378.661088,4.82,4.82,0.69400,-0.36
173,86980,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Ray, Johnny","$5,511,000",2B,S,1982,rayjo01,0,...,NaN,NaN,NaN,NaN,NaN,7305.832148,24.18,24.18,3.87575,3.81
174,86989,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Thornton, Andre","$6,439,000","DH, 1B",R,1982,thornan01,0,...,NaN,NaN,NaN,NaN,NaN,8564.971751,7.00,7.00,2.06325,2.84
175,86978,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Upshaw, Willie","$4,181,000",1B,L,1982,upshawi01,0,...,NaN,NaN,NaN,NaN,NaN,5891.640867,14.84,14.84,2.50750,1.45
176,86976,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Virgil, Ozzie","$1,259,000",C,R,1982,virgioz02,1,...,NaN,NaN,NaN,NaN,NaN,7963.963964,9.25,9.25,0.74700,-0.08
177,86987,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4D43798954B3C4DD5,"Wilson, Mookie","$6,487,000",CF,S,1982,wilsomo01,0,...,53.0,2.0,NaN,NaN,4.0,9028.064993,20.90,20.90,2.50175,1.95
178,87068,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Barfield, Jesse","$3,017,000","RF, LF, CF",R,1982,barfije01,1,...,213.0,4.0,213.0,3.0,2.0,5923.766816,38.88,38.88,2.97025,1.07
179,87084,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Bass, Kevin","$500,000","RF, LF, CF",S,1982,basske01,1,...,133.0,4.0,133.0,4.0,4.0,3571.428571,14.82,14.82,0.15525,-1.25
180,87069,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Clark, Jack","$11,266,000",RF,R,1982,clarkja01,1,...,NaN,NaN,93.0,3.0,1.0,16526.555387,32.71,32.71,3.35000,3.99
181,87059,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Fisk, Carlton","$5,393,000","C, 1B",R,1982,fiskca01,1,...,NaN,NaN,NaN,NaN,NaN,9361.940299,26.11,26.11,2.83775,3.33
182,87066,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Gibson, Kirk","$4,218,000",CF,L,1982,gibsoki01,2,...,42.0,3.0,NaN,NaN,3.0,13071.428571,36.24,36.24,2.95425,1.88
183,87061,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Grich, Bobby","$5,644,000",2B,R,1982,grichbo01,1,...,NaN,NaN,NaN,NaN,NaN,8709.090909,14.59,14.59,3.25975,3.68
184,87070,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Heep, Danny","$1,380,000","RF, 1B, LF",L,1982,heepda01,1,...,NaN,NaN,68.0,3.0,4.0,4527.027027,0.03,0.03,0.12475,0.13
185,87062,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Kennedy, Junior","$500,000","2B, 3B, SS",R,1982,kenneju01,1,...,NaN,NaN,NaN,NaN,NaN,461.254613,-0.89,-0.89,-0.30000,-0.57
186,87067,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Lynn, Fred","$10,438,000",CF,L,1982,lynnfr01,1,...,52.0,3.0,NaN,NaN,3.0,18464.220183,18.00,18.00,3.31650,4.70
187,87072,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"McRae, Hal","$11,516,000","DH, LF",R,1982,mcraeha01,0,...,NaN,NaN,NaN,NaN,3.0,16480.769231,6.92,6.92,2.23325,4.13
188,87064,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Molitor, Paul","$10,834,000","3B, SS",R,1982,molitpa01,0,...,NaN,NaN,NaN,NaN,NaN,13926.764314,62.57,62.57,4.12625,6.22
189,87071,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Monday, Rick","$3,735,000","RF, 1B, LF",L,1982,mondari01,1,...,NaN,NaN,158.0,4.0,4.0,13228.346457,1.29,1.29,0.50175,1.18
190,87060,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Newman, Jeff","$616,000","C, 1B, 3B",R,1982,newmaje01,1,...,NaN,NaN,NaN,NaN,NaN,899.253731,-1.67,-1.67,-0.55600,-1.11
191,87065,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Wallach, Tim","$10,557,000","3B, 1B",R,1982,wallati01,1,...,NaN,NaN,NaN,NaN,NaN,15786.046512,37.79,37.79,4.20975,4.44
192,87063,E7EH6QL4Y64GYX7LZXF6,C495D44BBA0C49D4F7B8E4092C7CF8C1,"Wilfong, Rob","$510,000","2B, 3B, SS, LF",L,1982,wilforo01,1,...,NaN,NaN,NaN,NaN,3.0,671.641791,1.86,1.86,0.32725,0.38